import Head from 'next/head';

import Header from '../components/Header';
import Posts from '../components/Posts';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home() {


  return (
    <div className="h-screen  overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    
      
       
      
         <Header/>
       <main className="flex">
       <Sidebar/>
       <Posts/>
       <Widgets/>
   
       </main>
     
         

      
     
      
    </div>
  )
}


