import Head from 'next/head';

import Follow from '../components/follow';
import Header from '../components/Header';
import Post from '../components/Post';
import Sidebar from '../components/Sidebar';
import { db } from '../firebase';

export default function Home({posts}) {
  console.log(posts)
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
       <div className="flex flex-col overflow-x-hidden">
      <Header/>
      <div className="flex flex-grow mt-20  ml-20  mr-20">
      <Sidebar/>

      <Post posts={posts}/>

      <Follow/>

      </div>

      </div>
     
      
    </div>
  )
}


export async function getStaticProps() { 

 const posts = await db.collection("posts").orderBy("timestamp", "desc").get();
  const docs = posts.docs.map((post) => [
    {
      id: post.id,
      ...post.data(),
      timestamp: null,
    },
  ]);
  return {
    props: {
      
      posts: docs,
    },
  };

}